### ISSUE TITLE
sendMessageToPhoneGroup is not working properly

### ISSUE THREAD

**Issue by level09** [issuestand/django-ios-push#5]
from the command line, tried to broadcast a message using that method but nothing happened (returned nothing). 

```
In [8]: models.sendMessageToPhoneGroup(models.Device.objects.all(), alert='test message')

In [9]: 
```

while sending a message to a single device seems to work, returns True. 

does this mean it has to do with the socket implementation ? 

how can I possibly investigate the issue ? 

Thanks in advance

**Comment by level09** [comment]
I have decreased the chunk size to 40, and it seems to work fine .. will keep monitoring it for some time.. 

by the way, running this on a medium ec2 instance, and handling around 2000 devices, should I consider upgrading the server ? what specifically should I be scaling ?

**Comment by suda** [comment]
Apple doesn't specify maximum number of notifications that can be send in one connection, so chunk size value is set experimentally so it won't disconnect. You can increase EC2 instance, but if your notifications can be sent with slight delay, I would recommend to tweak chunk size.

I'll have to move this value to settings and throw an exception when chunk is too big.

**Comment by level09** [comment]
Thanks This seems to be solved after tweaking the chunk size and tweaking the server.
