### ISSUE TITLE
Support Apple's enhanced notification format 

### ISSUE THREAD

**Issue by level09** [issuestand/django-ios-push#6]
Hi ,

is there any plans to support this ? looks like the old format has a limitation when it comes to UTF8 strings (actual length allowed would be around 40 characters).

**Comment by suda** [comment]
Hi Nidal, https://github.com/appsome/django-ios-push/commit/f5787034529fa938a7d252bb27aeb1f176a6a27b adds support for ENF and should solve UTF8 issues :)

**Comment by level09** [comment]
Excellent ! thanks
